services:
  db:
    image: mariadb:lts
    ports:
      - "3306:3306"
    container_name: mariadb_host
    environment:
      MARIADB_ROOT_PASSWORD: foobarhogepiyo
    volumes:
      - db-data:/var/lib/mysql
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data: