spring:
  application:
  name: book-manager
  datasource:
    url: jdbc:mariadb://localhost:3306/book_manager
    username: book_manager
    password: s23024NAHA
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
